server:
  port: 18080

#admin: liusc


#将服务注册到eureka
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.119:8080/eureka
#因为该应用为注册中心，不会注册自己
    register-with-eureka: true
#是否需要从eureka上获取注册信息
    fetch-registry: true


spring:
  application:
    name: spring-boot230
#  redis:
#    host: 192.168.0.199
#    database: 0
#    port: 6379
#    password:


redisLock : redis_lock